### ISSUE TITLE
Revisar las declaraciones

### ISSUE THREAD

**Issue by gdeldago** [escuela-tecnica-21/ta-te-ti-Francocarabajal78#2]
https://github.com/escuela-tecnica-21/ta-te-ti-Francocarabajal78/blob/9bd81db2351e2307fedd3094a669251b3b8d8c83/main.c#L6-L8

Recordá que en la declaración de una función se deben explicitar los argumentos.

**Comment by Francocarabajal78** [comment]
profe con explicitar los argumentos, se refiere a que tengo que poner los argumentos que declare en la función no?

**Comment by gdeldago** [comment]
Exacto :) tal como lo hiciste ahora.
